# Form implementation generated from reading ui file 'd:\учеба\бд\курсач\brewery\front\authorisation\authorisation_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthorisationWindow(object):
    def setupUi(self, AuthorisationWindow):
        AuthorisationWindow.setObjectName("AuthorisationWindow")
        AuthorisationWindow.resize(500, 450)
        AuthorisationWindow.setBaseSize(QtCore.QSize(505, 486))
        self.centralwidget = QtWidgets.QWidget(AuthorisationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.username_line_edit.setGeometry(QtCore.QRect(160, 200, 171, 21))
        self.username_line_edit.setObjectName("username_line_edit")
        self.password_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_line_edit.setGeometry(QtCore.QRect(160, 250, 171, 21))
        self.password_line_edit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.sign_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in_button.setGeometry(QtCore.QRect(180, 300, 131, 31))
        self.sign_in_button.setObjectName("sign_in_button")
        self.sign_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_up_button.setGeometry(QtCore.QRect(200, 360, 91, 31))
        self.sign_up_button.setObjectName("sign_up_button")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(170, 180, 61, 16))
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(170, 230, 61, 16))
        self.password_label.setObjectName("password_label")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(50, 80, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.sign_up_label = QtWidgets.QLabel(self.centralwidget)
        self.sign_up_label.setGeometry(QtCore.QRect(190, 340, 121, 16))
        self.sign_up_label.setObjectName("sign_up_label")
        self.invalid_auth_label = QtWidgets.QLabel(self.centralwidget)
        self.invalid_auth_label.setGeometry(QtCore.QRect(170, 280, 161, 16))
        self.invalid_auth_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.invalid_auth_label.setObjectName("invalid_auth_label")
        AuthorisationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthorisationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorisationWindow)

    def retranslateUi(self, AuthorisationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorisationWindow.setWindowTitle(_translate("AuthorisationWindow", "MainWindow"))
        self.sign_in_button.setText(_translate("AuthorisationWindow", "Sign in"))
        self.sign_up_button.setText(_translate("AuthorisationWindow", "Sign up"))
        self.username_label.setText(_translate("AuthorisationWindow", "Username"))
        self.password_label.setText(_translate("AuthorisationWindow", "Password"))
        self.welcome_label.setText(_translate("AuthorisationWindow", "Welcome to Nyakutka\'s Brewery!"))
        self.sign_up_label.setText(_translate("AuthorisationWindow", "Don\'t have an account?"))
        self.invalid_auth_label.setText(_translate("AuthorisationWindow", "Invalid username or password"))
